### ISSUE TITLE
llvm binaries

### ISSUE THREAD

**Issue by cxleb** [flax-lang/flax#21]
On windows specifically how and where do we get the libllvm binaries from or do we compile them from source because i am probably missing something obvious

**Comment by zhiayang** [comment]
Unfortunately you need to compile them from source. Use cmake and follow the instructions on the llvm site, I guess.

**Comment by cxleb** [comment]
Alright thatll have to do i guess

**Comment by zhiayang** [comment]
Note: I've recently put up a set of compiled libraries for our dependencies for use by the CI platform: https://github.com/flax-lang/flax/releases/tag/win-build-deps
