### ISSUE TITLE
"Поссия" instead of "Россия" in the docs

### ISSUE THREAD

**Issue by Neverik** [flax-lang/flax#27]
The latter is the proper way to spell it. The mistake is in: http://flax-lang.github.io/content/strings.html

Or was it intentional?

**Comment by Neverik** [comment]
Also, the link to the `functions` section (and everything after that) is broken.

**Comment by zhiayang** [comment]
Docs need a complete rewrite, so I'll close this for now. I copied that from somewhere so idk what was up with that.
