### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by ghost** [flax-lang/flax#43]
@zhiayang

**Comment by ghost** [comment]
@tobiasvl @zhiayang @Philpax @adrian17

**Comment by ghost** [comment]
Where can I ask a question?

**Comment by tobiasvl** [comment]
@t0md3an What do you mean? You just asked a question here, so why not ask it here? Why did you mention me? I'm very confused.

**Comment by zhiayang** [comment]
this person has opened 20 issues in 9 other prog-lang repositories, and has a tendency to @ any and all repo contributors to get attention.

i'm not free to work on flax for now, the best documentation you can get is by looking at the tests.

**Comment by tobiasvl** [comment]
Right. I'd totally forgotten that I contributed a fix to a URL in the README in this repo four years ago.

**Comment by ghost** [comment]
Sorry guys. @zhiayang You said I can explore flax from tests, but I can't find any examples of Flax.

**Comment by zhiayang** [comment]
they are under `build/tests`.
